/**
 * Canonical controlled vocabularies for product/look forms.
 *
 * Single source of truth for the values an operator may pick when creating or
 * editing a product. Filter drawers may still narrow these down to values that
 * actually occur in the catalogue, but every *input* form should offer the full
 * list from here so the data stays consistent.
 *
 * Ported and adapted from the legacy `datas/FormSelectionValues.json`:
 * category keys use this project's English `ProductCategory` enum, while the
 * displayed values keep the French fashion vocabulary.
 */
import type { ProductCategory } from '@/types'

// Product types, grouped by category.
export const PRODUCT_TYPES: Record<ProductCategory, readonly string[]> = {
  top: [
    'Veste',
    'Sweat',
    'Top',
    'Blouse/Chemise',
    'Blouson',
    'Pull/Maille',
    'Tailleur',
    'Manteau',
    'Cardigan',
  ],
  bottom: ['Jean', 'Jupe', 'Short', 'Pantalon'],
  shoes: [
    'Bottes',
    'Boots',
    'Escarpin',
    'Espadrille',
    'Ballerine',
    'Basket',
    'Tong',
    'Sabot',
    'Sandale',
    'Chaussettes',
    'Mocassin',
  ],
  accessories: [
    'Cabas',
    'Ceinture',
    'Panier',
    'Pochette',
    'Foulard',
    'Valise',
    'Sac banane',
    'Sac de voyage',
    'Sac à main',
    'Bijoux',
    'Serre-Tête',
    'Barette',
    'Chapeau/Bonnet/Gants',
    'Lunettes',
    'Maroquinerie',
  ],
  set: ['Combinaison', 'Pyjama', 'Robe', 'Ensemble', 'Bain'],
} as const

// Flat list of every product type, across all categories.
export const ALL_PRODUCT_TYPES: readonly string[] = Object.values(PRODUCT_TYPES).flat()

export const COLORS: readonly string[] = [
  'Parme',
  'Noir',
  'Orange',
  'Marine',
  'Gris',
  'Anthracite',
  'Vert',
  'Beige',
  'Bleu',
  'Rose',
  'Blanc',
  'Violet',
  'Rouge',
  'Ecru',
  'Kaki',
  'Jaune',
  'Marron',
  'Taupe',
  'Bordeaux',
  'Bleu Ciel',
  'Doré',
  'Nude',
  'Ocre',
  'Camel',
  'Turquoise',
  'Argent',
  'Bleu Canard',
  'Bronze',
  'Fuschia',
] as const

export const DETAILS: readonly string[] = [
  'Uni',
  'Fleuri',
  'Carreaux',
  'Jacquard',
  'Flanel',
  'Chevron',
  'Imprimé Pois',
  'Tweed',
  'Imprimé',
  'Rayure',
  'Impression',
  'Fleur',
  'Satin',
  'Pièces Métaliques Or',
  'Bicolore',
  'Imprimé Fleur',
  'Jersey',
  'Broderie',
  'Crochet',
  'Ecossais',
  'Voile',
  'Chine',
  'Broche',
  'Stone',
  'Ribb',
  'Ajouré',
  'Tissé',
  'Or',
  'Damier',
  'Embosse',
  'Animal Print',
  'Vichy',
  'Velours',
  'Patchwork',
  'Gabardine',
  'Mousseline',
  'Organza',
  'Paillettes',
  'Logo',
] as const

export const MATERIALS: readonly string[] = [
  'Acetate',
  'Angora',
  'Bois',
  'Cachemire',
  'Coton',
  'Coton Enduit',
  'Coton Satin',
  'Cuir',
  'Cuir Vernis',
  'Daim',
  'Duvet',
  'Elasthane',
  'Feutre',
  'Fourrure',
  'Jean',
  'Laine',
  'Latex',
  'Lezard',
  'Lin',
  'Lurex',
  'Lycra',
  'Metal Argenté',
  'Metal Doré',
  'Mouton',
  'Nylon',
  'Polyester',
] as const

// Clothing sizes (FR system) — used for `sizes` on top/bottom/set/accessories.
export const CLOTHING_SIZES: readonly string[] = [
  '36',
  '38',
  '40',
  '42',
  '44',
  '46',
  '48',
  '50',
  '52',
  '54',
  '56',
  '58',
  '60',
  'Taille Unique',
] as const

// Shoe sizes (EU system) — used for `shoe_sizes` on the shoes category.
export const SHOE_SIZES: readonly string[] = [
  '31',
  '32',
  '33',
  '34',
  '34.5',
  '35',
  '35.5',
  '36',
  '36.5',
  '37',
  '37.5',
  '38',
  '38.5',
  '39',
  '39.5',
  '40',
  '40.5',
  '41',
  '41.5',
  '42',
  '42.5',
  '43',
  '43.5',
  '44',
  '44.5',
  '45',
  '45.5',
  '46',
  '46.5',
  '47',
  '47.5',
  '48',
  '48.5',
  '49',
  '50',
  '50.5',
  '51',
  '51.5',
  '52',
  '52.5',
  '53',
  '53.5',
  '54',
  '54.5',
  '55',
  'Taille Unique',
] as const

/** Product types available for a given category (empty array if unknown). */
export function typesForCategory(category: ProductCategory): readonly string[] {
  return PRODUCT_TYPES[category] ?? []
}
